-- SCHEMA HISTORY
SELECT * FROM ECU_POLICY."schema_history" WHERE "description" LIKE '%INC23703493%';

-- REN DATA
SELECT COUNT(F.ID) FROM ECU_POLICY.FIXED_RENEWAL_DATA F WHERE F.YEAR = '2026' AND F.MONTH = '7';

-- REN DATA BLOQUEADO (no_renovar_count)
SELECT COUNT(F.ID) FROM ECU_POLICY.FIXED_RENEWAL_DATA F WHERE F.YEAR = '2026' AND F.MONTH = '7' AND BLOCKED_RENEWAL = 'YES';